export const CREATE_CLAIM_ALIAS = 'CREATE_CLAIM_ALIAS';
export const ASK_CLAIM_ALIAS = 'ASK_CLAIM_ALIAS';
export const SET_PASSWORD_ALIAS = 'SET_PASSWORD_ALIAS';
export const CHECK_PASSWORD_ALIAS = 'CHECK_PASSWORD_ALIAS';
export const GET_PASSWORD_ALIAS = 'GET_PASSWORD_ALIAS';

export const SET_WALLET = 'SET_WALLET';
export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_CLAIM = 'SET_CLAIM';
export const DESTROY_CLAIM = 'DESTROY_CLAIM';
export const TOGGLE_DIALOG = 'TOGGLE_DIALOG';
export const SEND_ERROR = 'SEND_ERROR';
export const DESTROY_ERROR = 'DESTROY_ERROR';
export const SET_HASH = 'SET_HASH';
export const DESTROY_HASH = 'DESTROY_SESSION';
export const SET_SESSION = 'SET_SESSION';
export const DESTROY_SESSION = 'SET_SESSION';
